<?php

/**
 * @file
 * Contains \Drupal\group\Entity\Form\GroupContentApproveForm.
 */

namespace Drupal\cust_group\Form;

use Drupal\Core\Form\ConfirmFormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Provides a form for deleting a group content entity.
 */
class GroupContentApproveForm extends ConfirmFormBase {
  
  
  public function __construct(RouteMatchInterface $routeMatch) {
    $this->entity = $routeMatch->getParameter('group_content');
  }
  
  public static function create(ContainerInterface $container) {
    return new static($container->get('current_route_match'));
  }
  
  public function getFormId() {
    return "approve_membership_request";
  }
  
  /**
   * {@inheritdoc}
   */
  public function getQuestion() {
    return $this->t('Are you sure you want to approve %name?', ['%name' => $this->entity->label()]);
  }
  
  /**
   * {@inheritdoc}
   */
  public function getCancelURL() {
    // @todo Read a redirect from the plugin?
    $entity = $this->entity;
    return new Url('view.hzd_group_members.pending', ['group' => $entity->getGroup()->id()]);
  }
  
  /**
   * {@inheritdoc}
   */
  public function getConfirmText() {
    return $this->t('Approve');
  }
  
  /**
   *
   */
  public function validateForm(array &$form, FormStateInterface $form_state) {
    parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
  }
  
  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $entity = $this->entity;
    $entity->request_status = 1;
    $entity->save();
    
    \Drupal::logger('group_content')->notice('@type: approved %title.', [
      '@type' => $this->entity->bundle(),
      '%title' => $this->entity->label(),
    ]);
    // @todo Read a redirect from the plugin?
    $form_state->setRedirect('view.hzd_group_members.pending', ['group' => $entity->getGroup()->id()]);
  }
  
}
