label: 'Neuester Inhalt'
description: 'Neuer Inhalt.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      title: 'Neuester Inhalt'
      empty:
        area_text_custom:
          content: 'Kein Inhalt verfügbar.'
