display:
  default:
    display_options:
      filters:
        status:
          group_info:
            group_items:
              1:
                value: '1'
              3:
                title: Blocked
      fields:
        status:
          alter:
            text: "{% if uid == 1 and status__value == 1 %}\r\nInactive\r\n{% elseif uid == 0 and status__value == 1 %}\r\nActive\r\n{% elseif uid == 1 and status__value == 0 %}\r\nBlocked\r\n{% elseif uid == 0 and status__value == 0 %}\r\nBlocked\r\n{% endif %}\r\n"
