label: 'Neue Mitglieder'
description: 'Zeigt eine Liste der neuesten Benutzerkonten auf der Webseite.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      title: 'Neue Mitglieder'
  block_1:
    display_title: 'Neue Mitglieder'
    display_options:
      display_description: 'Eine Liste neuer Benutzer'
      block_description: 'Neue Mitglieder'
      block_category: Benutzer
