label: Dateien
display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
      fields:
        filemime:
          label: 'Mime type'
        filesize:
          label: Größe
        created:
          label: 'Upload Datum'
        changed:
          label: 'Datum geändert'
        count:
          label: 'Verwendet in'
      filters:
        filename:
          expose:
            label: Dateiname
        filemime:
          expose:
            label: 'Mime type'
      title: Dateien
      empty:
        area_text_custom:
          content: 'Keine Dateien verfügbar'
  page_1:
    display_title: Dateiübersicht
    display_options:
      menu:
        title: Dateien
  page_2:
    display_options:
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
      fields:
        entity_label:
          label: Entität
        type:
          label: Entitätstyp
        count:
          label: 'Anzahl der Verwendung'
      arguments:
        fid:
          exception:
            title: Alle
          title: 'Dateiverwendungsinformationen für {{ arguments.fid }}'
