display:
  default:
    display_options:
      filters:
        status:
          group_info:
            group_items:
              1:
                value: '1'
      exposed_form:
        options:
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
      title: Inhalt
  page_1:
    display_options:
      menu:
        title: Inhalt
      tab_options:
        title: Inhalt
label: Inhalt
description: 'Die Inhalte finden und verwalten.'
