label: 'Bibliothek benutzerdefinierter Blöcke'
description: 'Benutzerdefinierte Blöcke finden und verwalten.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Anwenden
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
      title: 'Bibliothek benutzerdefinierter Blöcke'
  page_1:
    display_options:
      menu:
        title: 'Bibliothek benutzerdefinierter Blöcke'
