label: 'Ausstehende Benutzer der {{ arguments.gid|placeholder }} '
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
      fields:
        created:
          label: 'Angefragt am'
        gid:
          label: 'Übergeordnete Gruppe'
        dropbutton:
          label: Operationen
      title: 'Ausstehende Benutzer der {{ arguments.gid|placeholder }} '
      empty:
        area_text_custom:
          content: 'Keine Daten vorhanden'
      arguments:
        gid:
          exception:
            title: Alle
  page_1:
    display_options:
      menu:
        title: 'Benutzer freischalten'
