label: 'Bibliothek benutzerdefinierter Blöcke'
description: 'Benutzerdefinierte Blöcke finden und verwalten.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
      fields:
        info:
          label: Blockbeschreibung
        type:
          label: 'Art des Blocks'
        changed:
          label: Aktualisiert
        operations:
          label: Operationen
      filters:
        info:
          expose:
            label: Blockbeschreibung
        type:
          expose:
            label: 'Art des Blocks'
      title: 'Bibliothek benutzerdefinierter Blöcke'
  page_1:
    display_options:
      menu:
        title: 'Bibliothek benutzerdefinierter Blöcke'
