module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  auto_nodetitle: 0
  automated_cron: 0
  block: 0
  block_class: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  composer_manager: 0
  config: 0
  config_direct_save: 0
  config_translation: 0
  contact: 0
  contextual: 0
  cust_address_book: 0
  cust_group: 0
  cust_user: 0
  custom_script_batch: 0
  custom_views_php: 0
  datetime: 0
  dblog: 0
  devel: 0
  downtimes: 0
  dynamic_page_cache: 0
  editor: 0
  entity_print: 0
  faq: 0
  faqfield: 0
  field: 0
  field_group: 0
  field_group_migrate: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filefield_paths: 0
  filter: 0
  front: 0
  gnode: 0
  group: 0
  help: 0
  history: 0
  hzd_customizations: 0
  hzd_earlywarnings: 0
  hzd_notifications: 0
  hzd_release_management: 0
  hzd_services: 0
  hzd_user_customizations: 0
  image: 0
  inactive_user: 0
  inline_entity_form: 0
  kint: 0
  l10n_client_contributor: 0
  l10n_client_ui: 0
  language: 0
  link: 0
  locale: 0
  masquerade: 0
  mass_contact: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  migrate_manifest: 0
  migrate_plus: 0
  migrate_tools: 0
  migrate_upgrade: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  pdf_api: 0
  printable: 0
  printable_pdf: 0
  problem_management: 0
  quickedit: 0
  rdf: 0
  reroute_email: 0
  rest: 0
  search_api: 0
  serialization: 0
  shortcut: 0
  simplify: 0
  statistics: 0
  subpathauto: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  ultimate_cron: 0
  update: 0
  user: 0
  view_unpublished: 0
  views_ui: 0
  xmlrpc: 0
  ctools: 1
  favorites: 1
  forum: 1
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  hzd: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
langcode: de
