favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://hzdupgrd-dev2.azri.de/themes/hzd/favicon.ico'
  use_default: 1
schema: '8000'
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://bpk.png'
  url: ''
  use_default: 0
cdn_provider_import_data: ''
breadcrumb_home: 1
schemas:
  bootstrap: 8000
  hzd: 8000
cdn_provider: jsdelivr
table: ''
