use_admin_theme: false
_core:
  default_config_hash: 2OMXCScXUOLSYID9-phjO4q36nnnaMWNUlDxEqZzG1U
notification_checkbox_article: 1
notification_checkbox_test: 1
notification_checkbox_quickinfo: 0
notification_checkbox_page: 1
