printable_entities:
  comment: comment
  node: node
  user: user
  block: '0'
  block_content: '0'
  contact_message: '0'
  file: '0'
  group: '0'
  group_content: '0'
  search_api_task: '0'
  shortcut: '0'
  taxonomy_term: '0'
  tour: '0'
  menu_link_content: '0'
open_target_blank: true
css_include: themes/hzd/css/entity-print.css
extract_links: '0'
save_pdf: false
pdf_tool: wkhtmltopdf
paper_size: A4
page_orientation: portrait
path_to_binary: /usr/local/bin/wkhtmltopdf
pdf_location: RZ-Schnellinfo-Nr-
send_to_printer: false
close_window: false
list_attribute: false
printable_print_link_locations:
  node: '0'
  comment: '0'
  user: '0'
printable_pdf_link_locations:
  - ''
_core:
  default_config_hash: 1Zx0Kjl4zSJQScIJ6Nv5z_DDYfYKiEzS-LRnLBoKZS8
langcode: de
