simplify_admin: false
simplify_nodes_global:
  author: author
  format: format
  options: options
  revision_information: revision_information
  comment: comment
  menu: menu
  path_settings: path_settings
simplify_users_global:
  format: format
  status: status
  timezone: timezone
  contact: contact
simplify_comments_global:
  format: format
simplify_taxonomies_global:
  format: format
  relations: relations
  path: path
simplify_blocks_global:
  format: format
  revision_information: revision_information
simplify_profiles_global: {  }
_core:
  default_config_hash: omWr4s_-ZB9DeG-rP5oY4s3Pm2uiK-guRhGg0_DHHpM
langcode: de
