<?php
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormState;
use Drupal\Core\Url;


function getErlywarningServies() {
  $group_id = get_group_id();
  
  $current_url = Url::fromRoute('<current>');
  $path = $current_url->toString();
  $current_path = explode("/", $path);
  $node = \Drupal::routeMatch()->getParameter('node');
  $nid = NULL;
  if ($node) {
    $nid = $node->id();
  }
  $query = \Drupal::database()->select('node_field_data', 'nfd');
  $query->Fields('nfd', array('type'));
  $query->condition('nfd.nid', $nid, '=');
  $type = $query->execute()->fetchField();
  
  if ($type == 'deployed_releases') {
    $services_releases = Drupal\hzd_release_management\HzdreleasemanagementHelper::released_deployed_releases();
    return $services_data = $services_releases['services'];
  }
  
  $group_id = ($group_id ? $group_id : RELEASE_MANAGEMENT);
  
  
  /**
   * $services_obj = db_query("SELECT title , n.nid FROM {node} n, {group_releases_view} grv
   * WHERE n.nid = grv.service_id and grv.group_id = %d ORDER by title ", $group_id);
   */
  
  //$services['none'] = " < " . t('Service') . ' > ';
  
  $query = \Drupal::database()->select('node_field_data', 'nfd');
  $query->join('group_releases_view', 'grv', 'nfd.nid = grv.service_id');
  $query->Fields('nfd', array('title', 'nid'));
  $query->condition('grv.group_id', $group_id, '=');
  $query->orderBy('title');
  $services = $query->execute()->fetchAllKeyed(1,0);
  return $services;
}

/**
 * implements hook_form_alter
 */
function hzd_earlywarnings_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_early_warnings_form') {
    $service = \Drupal::request()->query->get('services');
    $rel = \Drupal::request()->query->get('releases');
    $form['field_release_service']['widget']['#default_value'] = $service;
    $form['field_earlywarning_release']['widget']['#default_value'] = $rel;
    if ($rel && $service) {
      $form['field_release_service']['#attributes']['readonly'] = 'readonly';
      $form['field_earlywarning_release']['#attributes']['readonly'] = 'readonly';
      $form['field_release_service']['#disabled'] = TRUE;
      $form['field_earlywarning_release']['#disabled'] = TRUE;
    }
    $form['field_release_service']['widget']['#ajax'] = [
      'callback' => 'hzd_early_warnings_service_change',
      'wrapper' => 'hzd-release-early-warnings',
    ];
    $form['field_earlywarning_release']['widget']['#prefix'] = '<div id="hzd-release-early-warnings">';
    $form['field_earlywarning_release']['widget']['#sufix'] = '</div>';
  }
  
  return $form;
}

function earlywarning_form_submit(&$form, FormState $formState) {
  $group = \Drupal::routeMatch()->getParameter('group');
  
}

/**
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function hzd_earlywarnings_node_insert(EntityInterface $entity) {
  if ($entity->getType() == 'early_warnings') {
    $group = \Drupal::routeMatch()->getParameter('group');
    $plugin = $group->getGroupType()
      ->getContentPlugin('group_node:early_warnings');
    
    $values = [
      'type' => $plugin->getContentTypeConfigId(),
      'gid' => $group->id(),
      'entity_id' => $entity->id(),
    ];
    $group_content = \Drupal::entityTypeManager()
      ->getStorage('group_content')
      ->create($values)
      ->save();
  }
}

function hzd_early_warnings_service_change(array &$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $service = $form_state->getValue('field_release_service')[0]['value'];
  $deployed_releses_options = released_deployed_releases($service)['releases'];
  natcasesort($deployed_releses_options);
  $form['field_earlywarning_release']['widget']['#options'] = $deployed_releses_options;
  return $form['field_earlywarning_release']['widget'];
}


/**
 * implements hook_form_alter
 */
function hzd_earlywarnings_comment_insert(Drupal\Core\Entity\EntityInterface $entity) {
  \Drupal::service('cache_tags.invalidator')
    ->invalidateTags(['earlywarning_list']);
}