<?php

/**
 * @file
 * Reroute Email module installation functions.
 */

/**
 * Implements hook_uninstall().
 */
function reroute_email_uninstall() {
  \Drupal::config('reroute_email.settings')->clear('reroute_email_address')->save();
  \Drupal::config('reroute_email.settings')->clear('reroute_email_enable')->save();
  \Drupal::config('reroute_email.settings')->clear('reroute_email_enable_message')->save();
}
