<?php

/**
 * @file
 * Hook implementations for the Views Merge Rows module.
 */

declare(strict_types = 1);

use Drupal\views\ViewExecutable;
use Drupal\views_merge_rows\HookHandler\ViewsPreRenderHookHandler;

/**
 * Implements hook_theme().
 */
function views_merge_rows_theme($existing, $type, $theme, $path) {
  return [
    'merge_rows_theme' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Implements hook_views_pre_render().
 *
 * Merges the rows according to the settings for current display.
 */
function views_merge_rows_views_pre_render(ViewExecutable $view) {
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(ViewsPreRenderHookHandler::class)
    ->process($view);
}
