<?php

/**
 * @file
 * Contains cust_pdf.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cust_pdf_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cust_pdf module.
    case 'help.page.cust_pdf':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module to handle custom pdf generation functions') . '</p>';
      return $output;

    default:
  }
}


function cust_pdf_views_post_build(Drupal\views\ViewExecutable $view){
  $query = \Drupal::request()->query;
  if ($query->has('print') && $query->get('print') == 'pdf') {
    unset($view->exposed_widgets);
    unset($view->attachment_before);
    unset($view->attachment_after);
    $view->pager = new \Drupal\views\Plugin\views\pager\None([], '', []);
    $view->pager->init($view, $view->display_handler);
    $view->execute();
  }
//  unset($view->);
}
