<?php

/*function notifications_insert($nid, $type, $rel_type, &$context) {

  print "<pre>aaaa: ";
  print "asdasda";exit;
  error_log("qwertyuiop");
}*/

/**
 * implements hook_form_alter
 */
function hzd_services_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_services_edit_form' || $form_id == 'node_services_form') {
    $form['field_diff']['#prefix'] = "<div class = 'hzd-hide'>";
    $form['field_diff']['#suffix'] = '</div>';
    $form['upload']['#prefix'] = "<div class = 'hzd-hide'>";
    $form['upload']['#suffix'] = '</div>';
  }
  if($form_id == 'node_services_delete_form') {
    //print "<pre>";
    //print_r($form);exit;
  }

}
