display:
  default:
    display_options:
      fields:
        title:
          label: Title
        type:
          label: Type
      filters:
        type:
          expose:
            label: Type
        title:
          expose:
            label: Title
