module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  allowed_formats: 0
  anchor_link: 0
  auto_nodetitle: 0
  automated_cron: 0
  back_to_top: 0
  better_exposed_filters: 0
  block: 0
  block_class: 0
  block_content: 0
  block_upload: 0
  block_visibility_groups: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  colorbutton: 0
  comment: 0
  computed_field: 0
  config: 0
  config_direct_save: 0
  config_translation: 0
  contact: 0
  contextual: 0
  cust_address_book: 0
  cust_group: 0
  cust_node: 0
  cust_pdf: 0
  cust_user: 0
  custom_script_batch: 0
  custom_views_php: 0
  date_popup: 0
  datetime: 0
  dblog: 0
  downtimes: 0
  draggableviews: 0
  dynamic_page_cache: 0
  editor: 0
  entity_print: 0
  entity_print_views: 0
  entity_reference_exposed_filters: 0
  faq: 0
  faqfield: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filefield_paths: 0
  filter: 0
  front: 0
  gforum: 0
  gnode: 0
  group: 0
  history: 0
  hzd_customizations: 0
  hzd_earlywarnings: 0
  hzd_notifications: 0
  hzd_release_inprogress_comments: 0
  hzd_risk_management: 0
  hzd_services: 0
  hzd_user_customizations: 0
  image: 0
  imce: 0
  inactive_user: 0
  kint: 0
  l10n_client_contributor: 0
  l10n_client_ui: 0
  language: 0
  link: 0
  locale: 0
  login_emailusername: 0
  mailsystem: 0
  masquerade: 0
  mass_contact: 0
  matomo: 0
  menu_ui: 0
  migrate: 0
  node: 0
  options: 0
  page_cache: 0
  panelbutton: 0
  path: 0
  pdf_api: 0
  persistent_login: 0
  prlp: 0
  problem_management: 0
  queue_ui: 0
  quickedit: 0
  rdf: 0
  revision_log: 0
  search: 0
  search_api: 0
  search_api_solr: 0
  serial: 0
  serialization: 0
  simple_block: 0
  simplify: 0
  statistics: 0
  subpathauto: 0
  swiftmailer: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  view_unpublished: 0
  views_merge_rows: 0
  views_ui: 0
  xmlrpc: 0
  ctools: 1
  favorites: 1
  filefield_sources: 1
  forum: 1
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  ultimate_cron: 10
  views: 10
  reroute_email: 19
  queue_mail: 20
  hzd_release_management: 21
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  hzd: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
langcode: de
profile: standard
