maintenance_group_id: '19'
reminder_mail_subject: '[BpK] Ihre gemeldete Blockzeit'
reminder_mail_body:
  value: "<p>Hallo, das Ende Ihrer geplanten Blockzeit wurde überschritten. Bitte aktualisieren Sie das voraussichtliche Ende oder schließen Sie die Blockzeit nach bereits erfolgter Beendigung, andernfalls wird die Blockzeit in einer Woche automatisch geschlossen. Sie erreichen die Blockzeit direkt unter: [node:url] Viele Grüße, Team Betriebsportal KONSENS</p>\r\n"
  format: full_html
resolve_maintenance_mail_subject: '[BpK] Ihre gemeldete Blockzeit wurde geschlossen'
resolve_maintenance_mail_body:
  value: "<p>Hallo, das Ende Ihrer gemeldeten Blockzeit wurde überschritten. Wie vor einer Woche per Email angekündigt, haben wir die Blockzeit für Sie automatisch geschlossen. Sie müssen nun nichts mehr weiter unternehmen. Falls Ihre Blockzeit noch andauert, wenden Sie sich bitte an die Administratoren. Sie erreichen die Blockzeit direkt unter: [node:url] Viele Grüße, Team Betriebsportal KONSENS</p>\r\n"
  format: full_html
number_of_day: null
number_of_days: '7'
current_downtimes: "<p>Hier werden akute und geplante Ausfallzeiten länderübergreifender Systeme bekannt gegeben. Dies dient der schnellen Kommunikation von Betriebsstörungen, während die eigentliche Störungsbehebung über die vereinbarten Meldewege im jeweiligen Landesticket dokumentiert wird.</p>\r\n"
archived_downtimes: ''
report_downtimes: "<p><strong>Aktuelle Störung:</strong>&nbsp;Akuter Ausfall bzw. Nichterreichbarkeit eines Systems<br />\r\n<strong>Land:</strong> Das Land, in dem der Betrieb eines Verfahrens oder ZPS gestört ist.<br />\r\n<strong>Verfahren/ZPS:</strong> Verfahren oder ZPS, die durch die Störung nicht zur Verfügung stehen.<br />\r\n<br />\r\nIhre Meldung wird an alle&nbsp;Abonnenten der Benachrichtigungsoption \"Störungen und Blockzeiten\"&nbsp;versandt.&nbsp;<br />\r\n<br />\r\nBitte denken Sie unbedingt daran, Ihre Meldung zu gegebener Zeit wieder zu entfernen, um die Aktualität des BpK zu gewährleisten. Durch&nbsp;<i>Beheben</i>&nbsp;wird die Meldung in das Archiv verschoben.</p>\r\n"
report_downtimes_2: "<p>Wählen Sie das Land aus, in dem die Wartungsarbeiten ausgeführt werden. Mehrfachauswahl ist möglich.<br />\r\n&nbsp;</p>\r\n"
report_downtimes_3: "<p>Wählen Sie die Verfahren oder ZPS aus, die durch die Störung länderübergreifend nicht zur Verfügung stehen. Mehrfachauswahl ist möglich.<br />\r\n&nbsp;</p>\r\n"
notes_downtimes: "<p>Hier werden akute und geplante Ausfallzeiten länderübergreifender Systeme bekannt gegeben. Dies dient der schnellen Kommunikation von Betriebsstörungen, während die eigentliche Störungsbehebung über die vereinbarten Meldewege im jeweiligen Landesticket dokumentiert wird.</p>\r\n"
report_maintenance: "<p>Geplante Wartungs- und Blockzeiten, die sich auf länderübergreifende KONSENS-Verfahren auswirken, müssen - soweit sie an Arbeitstagen durchgeführt werden - dienstags und/oder mittwochs in der Zeit nach 18:00 Uhr durchgeführt werden <em>(Beschluss AutomSt III/2011 TOP K9).</em><br />\r\n<br />\r\n<strong>Geplante Blockzeit:</strong> Nichterreichbarkeit durch planmäßige Wartungsarbeiten<br />\r\n<strong>Land:</strong> Das Land oder System, in dem die Wartungsarbeiten ausgeführt werden.<br />\r\n<strong>Verfahren/ZPS:</strong> Verfahren oder ZPS, die durch die Wartungsarbeiten länderübergreifend nicht zur Verfügung stehen.<br />\r\n<br />\r\nBlockzeitmeldungen im BpK werden als regulär also konform mit dem <em>Beschluss AutomSt III/2011 TOP K9 </em> gewertet, wenn Beginn und Ende in der Zeit von Dienstag und Mittwoch 18:00 Uhr bis jeweils 05:59 des Folgetages liegen.<br />\r\nBis zum Abschluss gültiger SLAs wird für alle Verfahren eine Vorlaufzeit von 2 Tagen konfiguriert.<br />\r\nIhre Meldung wird an alle Abonnenten der Benachrichtigungsoption \"Störungen und Blockzeiten\" versandt.<br />\r\n<br />\r\nBitte denken Sie unbedingt daran, Ihre Meldung zu gegebener Zeit wieder zu entfernen, um die Aktualität des BpK zu gewährleisten. Durch Beheben wird die Meldung in das Archiv verschoben.</p>\r\n"
report_maintenance_2: "<p>Wählen Sie das Land aus, in dem die Wartungsarbeiten ausgeführt werden. Mehrfachauswahl ist möglich.&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n"
report_maintenance_3: "<p>Wählen Sie die Verfahren oder ZPS aus, die durch die Störung länderübergreifend nicht zur Verfügung stehen. Mehrfachauswahl ist möglich.<br />\r\n&nbsp;</p>\r\n"
maintenance_advance_time: '60'
howmany: 7
sitewide_maintenance_windows:
  -
    day_from: Tue
    day_to: Wed
    time_from: '18:00:00'
    time_to: '05:59:59'
  -
    day_from: Wed
    day_to: Thu
    time_from: '18:00:00'
    time_to: '05:59:59'
  -
    day_from: Sat
    day_to: Sun
    time_from: '00:00:00'
    time_to: '23:59:59'
langcode: de
