favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://hzdupgrd-migr.azri.de/themes/hzd/favicon.ico'
  use_default: 1
schema: '8000'
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: themes/hzd/images/hzd-logo.jpg
  url: ''
  use_default: 0
cdn_provider_import_data: ''
breadcrumb_home: 1
schemas:
  bootstrap: 8000
  hzd: 8000
cdn_provider: jsdelivr
region_wells:
  navigation: ''
  user_menu: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: well
  footer: ''
table: ''
