downtimes:
  subject_insert: '[[node:downtime_states]] Neue [node:downtime_type] ([node:downtime_services])'
  subject_update: '[[node:downtime_states]] Aktualisierte [node:downtime_type] ([node:downtime_services])'
  subject_cancel: '[[node:downtime_states]] Stornierte [node:downtime_type] ([node:downtime_services])'
  subject_resolve: '[[node:downtime_states]] Behobene [node:downtime_type] ([node:downtime_services])'
  mail_content: "<p>[node:url:absolute]</p>\r\n"
  mail_footer: "<p>[node:url:absolute]</p>\r\n\r\n<p>--<br />\r\nDies ist eine automatische Benachrichtigung vom Betriebsportal KONSENS. Falls Sie keine Benachrichtigungen mehr erhalten möchten, können Sie Ihre <a href=\"[user:user-notification-settings-url-absolute]\">Einstellungen für Benachrichtigungen ändern</a>.</p>\r\n"
  mail_view: 1
problems:
  subject: Hellooooooooooooo
  mail_content: '[node:created][node:created]'
quickinfo:
  subject_insert: '[[node:field_author_state]] RZ-Schnellinfo Nr. [node:field_unique_id] - [node:field_custom_title]'
  subject_update: '[[node:field_author_state]] RZ-Schnellinfo Nr. [node:field_unique_id] - [node:field_custom_title]'
  subject_cancel: null
  subject_resolve: null
  mail_content: "<p>[node:url:absolute]</p>\r\n"
  mail_footer: "<p>[node:url:absolute]</p>\r\n\r\n<p>--<br />\r\nDies ist eine automatische Benachrichtigung vom Betriebsportal KONSENS. Falls Sie keine Benachrichtigungen mehr erhalten möchten, können Sie Ihre <a href=\"[user:user-notification-settings-url-absolute]\">Einstellungen für Benachrichtigungen ändern</a>.</p>\r\n"
  mail_view: 1
planning_files:
  subject_insert: '[Release Management] Neue Planungsdatei: [node:title]'
  subject_update: '[Release Management] Neue Planungsdatei: [node:title]'
  subject_cancel: null
  subject_resolve: null
  mail_content: "<p>[node:url:absolute]</p>\r\n"
  mail_footer: "<p>[node:url:absolute]</p>\r\n\r\n<p>--<br />\r\nDies ist eine automatische Benachrichtigung vom Betriebsportal KONSENS. Falls Sie keine Benachrichtigungen mehr erhalten möchten, können Sie Ihre <a href=\"[user:user-notification-settings-url-absolute]\">Einstellungen für Benachrichtigungen ändern</a>.</p>\r\n"
  mail_view: 1
release:
  subject_insert: '[[node:field_relese_services:entity:title]] Neues Release: [node:title]'
  subject_update: '[[node:field_relese_services:entity:title]] Aktualisiertes Release: [node:title]'
  subject_cancel: null
  subject_resolve: null
  mail_content: "<p>[node:url:absolute]</p>\r\n"
  mail_footer: "<p>[site:url]/release-management/releases</p>\r\n\r\n<p>--<br />\r\nDies ist eine automatische Benachrichtigung vom Betriebsportal KONSENS. Falls Sie keine Benachrichtigungen mehr erhalten möchten, können Sie Ihre <a href=\"[user:user-notification-settings-url-absolute]\">Einstellungen für Benachrichtigungen ändern</a>.</p>\r\n"
  mail_view: 1
problem:
  subject_insert: '[[node:field_services:entity:title]] Neues Problem: [node:title]'
  subject_update: '[[node:field_services:entity:title]] Aktualisiertes Problem: [node:title]'
  subject_cancel: null
  subject_resolve: null
  mail_content: "<p>[node:url:absolute]</p>\r\n"
  mail_footer: "<p>[node:url:absolute]</p>\r\n\r\n<p>--<br />\r\nDies ist eine automatische Benachrichtigung vom Betriebsportal KONSENS. Falls Sie keine Benachrichtigungen mehr erhalten möchten, können Sie Ihre <a href=\"[user:user-notification-settings-url-absolute]\">Einstellungen für Benachrichtigungen ändern</a>.</p>\r\n"
  mail_view: 1
group_content:
  subject_insert: '[[node:content_group_title]] Neu - [node:content-type]: [node:title]'
  subject_update: '[[node:content_group_title]] Aktualisiert - [node:content-type]: [node:title]'
  subject_cancel: null
  subject_resolve: null
  mail_content: "<p>Group Content Updated again</p>\r\n"
  mail_footer: "<p>[node:url:absolute]</p>\r\n\r\n<p>--<br />\r\nDies ist eine automatische Benachrichtigung vom Betriebsportal KONSENS. Falls Sie keine Benachrichtigungen mehr erhalten möchten, können Sie Ihre <a href=\"[user:user-notification-settings-url-absolute]\">Einstellungen für Benachrichtigungen ändern</a>.</p>\r\n"
  mail_view: 1
early_warnings:
  subject_insert: '[[node:field_release_service]] Neue Early Warning: [node:title]'
  subject_update: '[[node:field_release_service]] Aktualisierte Early Warning: [node:title]'
  subject_cancel: null
  subject_resolve: null
  mail_content: "<p>[node:url:absolute]</p>\r\n"
  mail_footer: "<p>[node:url:absolute]</p>\r\n\r\n<p>--<br />\r\nDies ist eine automatische Benachrichtigung vom Betriebsportal KONSENS. Falls Sie keine Benachrichtigungen mehr erhalten möchten, können Sie Ihre <a href=\"[user:user-notification-settings-url-absolute]\">Einstellungen für Benachrichtigungen ändern</a>.</p>\r\n"
  mail_view: 1
group:
  subject_insert: '[[group:title]] Neue Gruppe'
  subject_update: '[[group:title]] Aktualisierte Gruppe'
  subject_cancel: null
  subject_resolve: null
  mail_content: "<p>[group:url]</p>\r\n"
  mail_footer: "<p>[node:url:absolute]</p>\r\n\r\n<p>--<br />\r\nDies ist eine automatische Benachrichtigung vom Betriebsportal KONSENS. Falls Sie keine Benachrichtigungen mehr erhalten möchten, können Sie Ihre <a href=\"[user:user-notification-settings-url-absolute]\">Einstellungen für Benachrichtigungen ändern</a>.</p>\r\n"
  mail_view: 1
