abs_urls: false
admin_theme: false
roles_profiles:
  authenticated:
    private: group_profile
  administrator:
    public: admin
    private: admin
  site_administrator:
    private: admin
_core:
  default_config_hash: 4FhrEwOM9yJ8neEoN77sxroTRBUXqRwap0KSJtFnYJs
langcode: de
