registration_terms_style: 3
registration_container: 0
login_terms_style: 1
login_container: 0
user_profile_display: false
accept_every_login: false
except_roles:
  administrator: administrator
  site_administrator: site_administrator
  authenticated: 0
  group_member: 0
  group_administrator: 0
registration_modal_terms: false
login_modal_terms: true
_core:
  default_config_hash: denrqScJlMiBdsks_UljTePRT-AAq-8PPlSluUFaxUs
langcode: de
confirm: aaaaa11sd
confirm_button_label: 'Datenschutzerklärung zustimmen'
reject_button_label: Zurück
legal_page_title: 'Bitte stimmen Sie unserer neuen Datenschutzerklärung zu'
legal_page_description:
  value: "<p><strong>Unsere Datenschutzerklärung wurde aktualisiert.</strong><br />\r\nDamit Sie den Funktionsumfang des Betriebsportals in gewohnter Weise nutzen können, benötigen wir Ihre Zustimmung zu unserer aktualisierten <a href=\"/datenschutz\">Datenschutzerklärung</a>.</p>\r\n"
  format: full_html
