registration_terms_style: 3
registration_container: 0
login_terms_style: 0
login_container: 0
user_profile_display: true
accept_every_login: false
except_roles:
  authenticated: authenticated
  administrator: administrator
  group_member: group_member
  group_administrator: group_administrator
  site_administrator: 0
registration_modal_terms: false
login_modal_terms: true
_core:
  default_config_hash: denrqScJlMiBdsks_UljTePRT-AAq-8PPlSluUFaxUs
langcode: de
confirm: aaaaa11sd
confirm_button_label: Confirm
reject_button_label: Decline
legal_page_title: 'Privacy Statements'
