_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
langcode: de
theme: current
defaults:
  sender: swiftmailer
  formatter: swiftmailer
modules:
  swiftmailer:
    none:
      sender: swiftmailer
      formatter: swiftmailer
  user:
    none:
      sender: php_mail
      formatter: php_mail
