use_admin_theme: false
_core:
  default_config_hash: 2OMXCScXUOLSYID9-phjO4q36nnnaMWNUlDxEqZzG1U
notification_checkbox_article: 1
notification_checkbox_test: 1
notification_checkbox_quickinfo: 0
notification_checkbox_page: 1
langcode: de
notification_checkbox_book: 1
notification_checkbox_early_warnings: 0
notification_checkbox_deployed_releases: 0
notification_checkbox_event: 0
notification_checkbox_forum: 0
notification_checkbox_grouppost: 0
notification_checkbox_non_production_environment: 0
notification_checkbox_planning_files: 0
notification_checkbox_problem: 0
notification_checkbox_release: 0
notification_checkbox_story: 0
notification_checkbox_service_profile: 0
notification_checkbox_services: 0
notification_checkbox_faqs: 1
notification_checkbox_news: 0
notification_checkbox_downtimes: 1
