noscript_tag_value: "<p>Für den vollständigen Funktionsumfang aktivieren Sie bitte Javascript in Ihren Browsereinstellungen oder benutzen Sie ggf. einen anderen Browser wie z.B. Chrome oder Firefox.</p>\r\n"
noscript_tag_format: basic_html
_core:
  default_config_hash: pGJJhjFtwi5R34k-PvksI57_nI-e3u-naFs6QOAjGvk
langcode: de
