noscript_tag_value: "<p>We noticed that your browser does not support Javascript. Please enable Javascript or use a different browser like Chrome or Firefox for using this website.</p>\r\n"
noscript_tag_format: basic_html
_core:
  default_config_hash: pGJJhjFtwi5R34k-PvksI57_nI-e3u-naFs6QOAjGvk
langcode: de
