_core:
  default_config_hash: pf1sgP08qOF1C19yVSs1Uxp0mlyDNa5YDUK2oO9vHKU
langcode: de
queue_mail_keys: "contact_*\r\ncust_group_*\r\nhzd_customizations_*\r\nhzd_notifications_*\r\ninactive_user_*\r\nmass_contact_*\r\nproblem_management_*\r\nreroute_email_*\r\nswiftmailer_*\r\nupdate_*\r\n"
queue_mail_queue_time: 45
queue_mail_queue_wait_time: 0
threshold: 50
requeue_interval: 10800
