actions: null
form_build_id: form-BlR91jgPv8mEBD5PR8KpvTWK-eeweFjOEvZyeX681OI
form_token: HNPLXfFtlw9b0w3m0BXRpHleG3nag3uPfLhzEmjROy0
form_id: reroute_email_settings
revision_log: null
revision: null
revision_information: null
whitelist: sandeep@azrisolutions.com
address: sandeep@azrisolutions.com
enable: true
description: true
langcode: de
