reroute_email_enable: 0
reroute_email_address: betriebsportal-konsens@hzd.hessen.de
reroute_email_enable_message: 1
actions: null
form_build_id: form-Q1jYAceg7T4pOemauPHUfnzzxK6R4W2j_Dhj0-GP-MM
form_token: dAXFnZJDjOF1fctk3V9CVV2lr934DLY5mNy-_uElj1I
form_id: reroute_email_settings
revision_log: null
revision: null
revision_information: null
whitelist: denis.roy@hzd.hessen.de
address: denis.roy@hzd.hessen.de
enable: true
description: true
langcode: de
message: false
mailkeys: ''
