_core:
  default_config_hash: 2dHO-FhZGuFtp-eL_9Gei7gp256jv6h5w9vK-ErZYvk
langcode: de
content_type: text/html
text_format: plain_text
generate_plain: false
character_set: UTF-8
format: text/html
respect_format: false
convert_mode: true
filter_format: plain_text
