<?php

/**
 * @file
 */

/**
 * Implements hook_user_cancel().
 */

/**
 *
 */
function inactive_user_user_cancel($edit, $account, $method) {
  \Drupal::database()->delete('inactive_users')
      ->condition('uid', $account->uid)
      ->execute();
}



/**
 * Implements hook_mail().
 */

/**
 * Function inactive_user_mail($key, &$message, $params) {.
 */
function inactive_user_mail($key, &$message, $params) {
  $message['subject'] = $params['subject'];
  $message['body'][] = $params['message'];
}

/**
 * Implements hook_schema().
 */
function inactive_user_schema() {
  $schema['inactive_users'] = array(
    'description' => 'The base table for inactive_users.',
    'fields' => array(
      'uid' => array(
        'description' => 'The primary identifier for a user.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'notified_admin' => array(
        'description' => 'Admin notifier.',
        'type' => 'int',
        'size' => 'tiny',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'notified_user' => array(
        'description' => 'User notifier.',
        'type' => 'int',
        'size' => 'tiny',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'warned_user_block_timestamp' => array(
        'description' => 'Timestamp warning.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'notified_user_block' => array(
        'description' => 'User block warning.',
        'type' => 'int',
        'size' => 'tiny',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'notified_admin_block' => array(
        'description' => 'Timestamp warning.',
        'type' => 'int',
        'size' => 'tiny',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'warned_user_delete_timestamp' => array(
        'description' => 'Timestamp warning.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'protected' => array(
        'description' => 'Timestamp warning.',
        'type' => 'int',
        'size' => 'tiny',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('uid'),
  );
  return $schema;
}
