display:
  address:
    display_options:
      filters:
        combine:
          expose:
            label: 'Name, E-Mail oder Benutzername'
        abbr:
          group_info:
            description: ''
