<?php

/**
 * @file
 * Contains Drupal\cust_filebrowser\cust_filebrowser.module
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\node\NodeInterface;

/**
 * Add class "cust-filebrowser-actions" to fix margin between buttons.
 *
 * Implements hook_ENTITY_TYPE_view_alter()
 */
function cust_filebrowser_node_view_alter(array &$build, NodeInterface $node, EntityViewDisplayInterface $display) {
  $view_mode = $display->getOriginalMode();
  if ($view_mode == 'full' && $node->bundle() == 'dir_listing') {
    // $build['filebrowser_file_list']['table2']['#markup'] = '<input class="form-control" id="myInput2" type="text" placeholder="Suche...">';
    $tableFilter = array(
      '#type' => 'textfield',
      "#placeholder" => "Tabelle filtern...",
      '#size' => 60,
      '#maxlength' => 128,
      '#required' => FALSE,
      '#id' => "search-files",
    );
    $prevArray = $build['filebrowser_file_list'];
    $result = array_slice($prevArray, 0, 4, true) +
      array("table_filter" => $tableFilter) +
      array_slice($prevArray, 4, count($prevArray) - 1, true) ;
    $build['filebrowser_file_list'] = $result;
    $build['filebrowser_file_list']['action']['#attributes']['class'][] = 'cust-filebrowser-actions';
  }
}

/**
 * Attaches the action_unblocker library to the page.
 * 
 * Enables the filebrowser action-buttons. Prevents action buttons from being 
 * clicked, before the page is fully loaded.
 * 
 * Implements hook_ENTITY_TYPE_view().
 */
function cust_filebrowser_node_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if ($view_mode == 'full' && $entity->bundle() == 'dir_listing') {
    $build['#attached']['library'][] = 'cust_filebrowser/action_unblocker'; //????
  }
}
