<?php

/**
 * @file
 * Contains Drupal\cust_filebrowser\cust_filebrowser.module
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\node\NodeInterface;

/**
 * Add class "form-actions" to fix margin between buttons.
 *
 * Implements hook_ENTITY_TYPE_view_valter()
 */
function cust_filebrowser_node_view_alter(array &$build, NodeInterface $node, EntityViewDisplayInterface $display) {
  $view_mode = $display->getOriginalMode();
  if ($view_mode == 'full' && $node->bundle() == 'dir_listing') {
    $build['filebrowser_file_list']['action']['#attributes']['class'][] = 'cust-filebrowser-actions';
  }
}
